# Generated by Django 5.0.6 on 2024-06-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_pokemon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(blank='', default='', upload_to='imagenes/'),
        ),
    ]
